# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START cloudbuild]
steps:
# This step runs the unit tests on the app
- name: 'python:3.7-slim'
  id: 'Run Tests'
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install flask && python test_app.py -v'

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: 'Create Container'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/hello-cloudbuild:$SHORT_SHA'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push to GCR Container Registry'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/hello-cloudbuild:$SHORT_SHA'
# [END cloudbuild]

# Update Manifest in Anthos Config Management Directory 

- name: 'gcr.io/anthos-tech-summit/gitops:1.0'
  id: 'Update Manifest'
  waitFor: ['Push to GCR Container Registry']
  entrypoint: 'bash'
  secretEnv: ['PASSWORD']
  args:
  - '-c' # pass what follows as a command to bash
  - |
    cd k8s/overlays/production
    kustomize edit set image ishmeetmehta/gcpDemo=gcr.io/$PROJECT_ID/gcpdemo:$BUILD_ID
    git clone https://github.com/IshmeetMehta/csp-config-management.git
    kustomize build > csp-config-management/tech-summit/namespaces/google/deployment.yaml
    cd csp-config-management/
    git config --global user.email "$_GIT_EMAIL"
    git config --global user.name "$_GIT_USER"
    git commit -am "manifest change $BUILD_ID"
    echo "Test:" $$PASSSWORD
    git push https://$_GIT_USER:$$PASSWORD@github.com/$_GIT_USER/csp-config-management.git

- id: 'Push to GKE'
  name: 'gcr.io/cloud-builders/kubectl' 
  waitFor: ['Update Manifest']
  args:
  - 'apply'
  - '-f'
  - 'k8s/overlays/production/csp-config-management/tech-summit/namespaces/google/deployment.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=$_CLOUDSDK_COMPUTE_ZONE'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER'



availableSecrets:
  secretManager:
  - versionName: projects/1046932852410/secrets/gh-password/versions/1
    env: 'PASSWORD'
