apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml
  - namespace.yaml

secretGenerator:
  - name: varsecretname
    files:
      - .dockerconfigjson=secrets/.dockerconfigjson
    type: kubernetes.io/dockerconfigjson
